name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cxxg-windows-latest-Release-cl.zip
          asset_name: cxxg-windows-latest-Release-cl.zip
          asset_content_type: application/zip
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cxxg-ubuntu-latest-Release-clang++.zip
          asset_name: cxxg-ubuntu-latest-Release-clang++.zip
          asset_content_type: application/zip
      - name: Upload MacOS artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cxxg-macos-latest-Release-clang++.zip
          asset_name: cxxg-macos-latest-Release-clang++.zip
          asset_content_type: application/zip
